### ISSUE TITLE
Step by Step Instructions Missing

### ISSUE THREAD

**Issue by ThomasCr** [auxesis/visage#12]
Hi,

I am really new to ruby and I really want to test this nice piece of software.

But sorry, the instructions are really bad :-(

What I did (I use Ubuntu Lucid):
aptitude install git-core libapache2-mod-passenger rake rubygems libsinatra-ruby libhaml-ruby librrd2-dev
git clone git://github.com/auxesis/visage.git
cd visage

than my knowledge stops:
bundle install vendor/gems/ give me only command not found

Any Help?

Regards,
Thomas

**Comment by auxesis** [comment]
Hi Thomas,
I've expanded the install instructions, let me know if you need any more help. 

Lindsay

**Comment by ThomasCr** [comment]
sorry, but there is nothing new to me.. all your have written I made before..

Where I get the bundle command??

**Comment by ThomasCr** [comment]
root@s01:/var/www/visage# gem install bundler
ERROR:  Error installing bundler:
    bundler requires RubyGems version >= 1.3.6
root@s01:/var/www/visage# dpkg -l|grep gems
ii  rubygems1.8                         1.3.5-1ubuntu2                    package management framework for Ruby libraries/applica

**Comment by ThomasCr** [comment]
ok,, i used now the newest rubygems package from ubuntu
root@s01:/var/www/visage# gem install bundler
ERROR:  Error installing bundler:
    bundler requires RubyGems version >= 1.3.6
root@s01:/var/www/visage# dpkg -l|grep gems
ii  rubygems1.9.1                       1.3.5-1ubuntu2                    package management framework for Ruby libraries/applica

but its not new enough :-( Really bad... and I use the Ubuntu Lucid distribution wihich is in development...

**Comment by auxesis** [comment]
Hi Thomas,
I can't really help you directly here, as the release of your distribution (Ubuntu Lucid) doesn't have the latest packages for RubyGems. If you want it to be sorted properly you'll have to ask the `bundler` guys why they feel it's necessary to make their software unusable by 95% of people, or with Ubuntu for not packaging the latest version of RubyGems. 

As other people are likely to have this problem with the latest bundler, I've temporarily converted Visage to use `bundler08` instead of `bundler`, which should work with the version of RubyGems you have available on Ubuntu Lucid.  

Try the new install instructions and let me know if they don't get you to where you want to be.

Lindsay
