### ISSUE TITLE
Getting 404's on profile

### ISSUE THREAD

**Issue by ghost** [auxesis/visage#41]
Hey,

I was able to install collectd on this server : http://stats.superfeedr.com/
I'm trying to create Profiles (not sure what they are though... some doc would help), but I get 404 eventually on all fo them.
anything I fucked up?

**Comment by auxesis** [comment]
Nah, my bad, I've fixed this in my highcharts branch, I'll cherrypick it across to master and push a new release.

**Comment by auxesis** [comment]
In the mean time, you can restart your Rack server (Passenger: restart apache, visage helper: ^C + start again) and the profiles will be there.

**Comment by superfeedr** [comment]
Nope :/ sorry, didn't work I get an ugly 500 with "syntax error on line 6, col 1: `: CPU-on-stats'"

http://stats.superfeedr.com/

**Comment by julien51** [comment]
Ok, its fixed... I had to delete the profiles file. I think there needs to be a semaphore somewhere to avoid race condition when writing to this file.

I have a ton more comments/questions. i guess I'll send u an email. For example, the scales are weird :/

**Comment by auxesis** [comment]
That makes sense. I believe I've fixed it in the other branch. 

Completely agree about the graph scales - it's a major reason why I've been looking into Highcharts instead of g.Raphael. 

If you want to try out the Highcharts version of Visage with all the bells and whistles, check out the repo, pull down the highcharts branch, and start it up with `bin/visage start`. 

Regardless, looking forward to your questions via email (or here :-).
